# Custom HawkEye header-style definitions, referenced from licenserc.toml via
# `additionalHeaders`. This overrides the built-in SLASHSTAR_STYLE (used for
# .js/.ts/.mjs) to add `skipLinePattern`, so a leading `#!` shebang is kept on
# line 1 and the license header is inserted after it. Without this, HawkEye
# places the block comment above the shebang, which is a syntax error in Node.

[SLASHSTAR_STYLE]
firstLine = '/*'
endLine = " */\n"
beforeEachLine = ' * '
afterEachLine = ''
skipLinePattern = '^#!.*$'
firstLineDetectionPattern = '(\s|\t)*/\*.*$'
lastLineDetectionPattern = '.*\*/(\s|\t)*$'
allowBlankLines = false
multipleLines = true
padLines = false
